;
; GENERATED FILE — rewritten by server/sip-provisioner.mjs on every agent login.
; Hand edits will be lost. See the header comment in git for the defaults.
; Last written: 2026-08-31T07:15:25.053Z
;

[2001-auth]
type=auth
auth_type=userpass
username=2001
password=auso-dev-2001
; static development default

[2002-auth]
type=auth
auth_type=userpass
username=2002
password=auso-dev-2002
; static development default

[2003-auth]
type=auth
auth_type=userpass
username=2003
password=auso-dev-2003
; static development default

[2004-auth]
type=auth
auth_type=userpass
username=2004
password=auso-dev-2004
; static development default

[2005-auth]
type=auth
auth_type=userpass
username=2005
password=auso-dev-2005
; static development default
