<?php

namespace App\Services;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * Issues short-lived SIP credentials for a browser phone (spec §2).
 *
 * The permanent PJSIP password must never reach the page. Instead we mint a
 * random password per agent session, store it where Asterisk can read it, and
 * expire it. If the page source leaks, the credential is useless once the
 * session ends.
 *
 * Two storage strategies:
 *
 *  - realtime (recommended): write to the `ps_auths` table Asterisk reads via
 *    res_config_odbc. No reload required; the change is live immediately.
 *  - ami: rewrite a pjsip auth include file and issue `pjsip reload`. Use only
 *    when realtime is not available.
 */
class SipCredentialProvisioner
{
    /** Cache key prefix for the live session credential. */
    private const CACHE_PREFIX = 'ausophone:sip:';

    public function __construct(
        private readonly ?AsteriskManager $ami = null,
    ) {
    }

    /**
     * @return array{password: string, expires_in: int, rotated: bool}
     */
    public function issue(string $extension, bool $force = false): array
    {
        if (config('ausophone.credential_strategy') === 'static') {
            return [
                'password'   => $this->staticPassword($extension),
                'expires_in' => (int) config('ausophone.credential_ttl'),
                'rotated'    => false,
            ];
        }

        $ttl = (int) config('ausophone.credential_ttl');
        $key = self::CACHE_PREFIX.$extension;

        // Reuse a live credential instead of rotating on every request.
        //
        // Rotating unconditionally breaks two ordinary cases: an agent with the
        // console open in two tabs, and the phone's own pre-expiry refresh —
        // each new password invalidates the other holder, which re-fetches and
        // invalidates back, forever. The credential is still short-lived; it is
        // bounded by the TTL, not by request count.
        if (! $force && ($existing = Cache::get($key))) {
            return [
                'password'   => $existing['password'],
                'expires_in' => max(1, $existing['expires_at'] - time()),
                'rotated'    => false,
            ];
        }

        // 24 bytes of URL-safe randomness: no ':' or '@' to break a SIP URI,
        // and far beyond brute-force for a credential that lives an hour.
        $password = Str::random(32);

        $this->persist($extension, $password);

        Cache::put($key, [
            'password'   => $password,
            'expires_at' => time() + $ttl,
        ], $ttl);

        return ['password' => $password, 'expires_in' => $ttl, 'rotated' => true];
    }

    /** Invalidate on logout so the endpoint cannot re-register (spec §13). */
    public function revoke(string $extension): void
    {
        Cache::forget(self::CACHE_PREFIX.$extension);

        if (config('ausophone.credential_strategy') === 'static') {
            return;
        }

        // Leave a password Asterisk will never be told, rather than deleting the
        // row — a missing auth section makes the endpoint unusable in a way
        // that is harder to diagnose.
        $this->persist($extension, Str::random(48));
    }

    private function persist(string $extension, string $password): void
    {
        if (config('ausophone.ami.enabled')) {
            $this->persistViaAmi($extension, $password);

            return;
        }

        $this->persistViaRealtime($extension, $password);
    }

    /**
     * PJSIP realtime: Asterisk reads ps_auths on every authentication, so an
     * UPDATE takes effect immediately with no reload.
     */
    private function persistViaRealtime(string $extension, string $password): void
    {
        $connection = config('ausophone.realtime_connection');

        DB::connection($connection)->table('ps_auths')->updateOrInsert(
            ['id' => $extension.'-auth'],
            [
                'auth_type' => 'userpass',
                'username'  => $extension,
                'password'  => $password,
            ],
        );
    }

    /**
     * Fallback: rewrite an included auth file and reload PJSIP. Slower and
     * racier than realtime — every reload re-reads the whole configuration.
     */
    private function persistViaAmi(string $extension, string $password): void
    {
        if (! $this->ami) {
            throw new RuntimeException('AMI strategy selected but AsteriskManager was not injected');
        }

        $path = storage_path('app/pjsip_auth.conf');
        $sections = $this->readSections($path);
        $sections[$extension] = $password;

        $body = "; GENERATED by SipCredentialProvisioner — do not edit\n\n";
        foreach ($sections as $ext => $secret) {
            $body .= "[{$ext}-auth]\ntype=auth\nauth_type=userpass\nusername={$ext}\npassword={$secret}\n\n";
        }

        // Write atomically: Asterisk must never read a half-written file.
        $tmp = $path.'.tmp';
        file_put_contents($tmp, $body);
        rename($tmp, $path);

        $this->ami->command('pjsip reload');

        Log::info('Rotated SIP credential', ['extension' => $extension]);
    }

    /** @return array<string, string> extension => password */
    private function readSections(string $path): array
    {
        if (! is_file($path)) {
            return [];
        }

        $out = [];
        $current = null;
        foreach (file($path, FILE_IGNORE_NEW_LINES) as $line) {
            if (preg_match('/^\[(\d+)-auth\]$/', trim($line), $m)) {
                $current = $m[1];
            } elseif ($current && preg_match('/^password\s*=\s*(.+)$/', trim($line), $m)) {
                $out[$current] = $m[1];
                $current = null;
            }
        }

        return $out;
    }

    private function staticPassword(string $extension): string
    {
        $password = DB::table('users')->where('extension', $extension)->value('sip_password');

        if (! $password) {
            throw new RuntimeException("No SIP password stored for extension {$extension}");
        }

        return decrypt($password);
    }
}
